[tool.poetry]
name = "mlx-llm-inference"
version = "0.1.0"
description = "MLX inference engine for LLM"
authors = ["ZetaLab <zeta9044@gmail.com>"]
packages = [{include = "mlx_llm_inference", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
mlx-llm-core = {path = "../mlx-llm-core", develop = true}
mlx = "^0.30"
mlx-lm = "^0.28"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
